format all python code
force python code to be formatted

Change-Id: I943b7b29ac3bb64007f9a2d494ea698e8561d427

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^(lib|include|tools)/.*\.(cpp|h|hpp)$')
+c_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^(lib|include|tools)/.*\.(cpp|h|hpp)$')
+py_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^(python|regression)/.*\.(py)$')
 RED='\033[0;31m'
 NC='\033[0m'
 
@@ -11,16 +12,39 @@ then
   exit 1
 fi
 
-if [ -n "$files" ]; then
+if ! command -v yapf &> /dev/null
+then
+  echo -e "${RED}ERROR${NC}: No yapf found, please install it with the following command.\n"
+  echo -e "\t pip3 install yapf\n"
+  exit 1
+fi
+
+if [ -n "$c_files" ]; then
     echo "Running clang-format on staged files..."
-    clang-format -i $files
+    clang-format -i $c_files
     if ! git diff --quiet; then
-        echo -e "${RED}Warning${NC}: Some files were formatted. Please review the changes and then commit it again."
+        echo -e "${RED}Warning${NC}: Some cpp files were formatted. Please review the changes and then commit it again."
         # git add $files
         exit 1
     fi
 fi
 echo "Success: clang-format check ok"
+
+if [ -n "$py_files" ]; then
+    echo "Running yapf on staged files..."
+    yapf -i --style .style.yapf $py_files
+    status=$?
+    if [ $status -ne 0 ]; then
+        echo -e "${RED}ERROR${NC}: yapf failed. Please check your code"
+        exit 1
+    fi
+    if ! git diff --quiet; then
+        echo -e "${RED}Warning${NC}: Some python files were formatted. Please review the changes and then commit it again."
+        # git add $files
+        exit 1
+    fi
+fi
+echo "Success: yapf check ok"
 
 PROJECT_ROOT=$(git rev-parse --show-toplevel)
 LIB_DIR="${PROJECT_ROOT}/third_party/nntoolchain/lib"
